### ISSUE TITLE
汇率动作不显示欧元

### ISSUE THREAD

**Issue by VincentCJ** [coo11/pin#2]
大佬好，pin+汇率动作无法显示欧元转换，请查看附件。
![image](https://user-images.githubusercontent.com/33440778/62448521-a1dd6b00-b79a-11e9-9a60-3d0268a7fd25.png)
![image](https://user-images.githubusercontent.com/33440778/62448533-a6098880-b79a-11e9-8bc3-82692af7cc77.png)
![image](https://user-images.githubusercontent.com/33440778/62448543-ab66d300-b79a-11e9-93f8-43a70033488e.png)

**Comment by coo11** [comment]
已解决，下版本更新
