### ISSUE TITLE
最新版本汇率查询有问题

### ISSUE THREAD

**Issue by ulpyuxa** [coo11/pin#5]
最新版本的汇率查询有问题，切换币种后，比重名称显示undefined，且汇率数据也没变
![022C8B98-7AEE-45A1-A8FB-9D357F2BAAC2](https://user-images.githubusercontent.com/16745176/67965177-85878800-fc3c-11e9-918b-062fab9831a1.jpeg)

**Comment by coo11** [comment]
已解决，更新即可
